import "./globals.css";
import { AuthProvider } from "@/auth/ProtectRouters";

export const metadata = {
  title: "Todo Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
